# Generated by Django 4.1.6 on 2023-02-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='subject_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
