# Generated by Django 4.1.6 on 2023-02-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_model', '0003_mymodel_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='classData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=100)),
            ],
        ),
    ]
