# Generated by Django 4.1.6 on 2023-02-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_model', '0004_classdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='semData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=100)),
            ],
        ),
    ]
